# Fastfile

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :build_ios do
    sh('pod install')
    build_app(
      scheme: "staging",
      export_method: "ad-hoc", # or "development" or "app-store"
      export_options: {
    allowProvisioningUpdates: true
  }
    )
  end

  desc "Push a new beta build for Flavor1 to Firebase"
  lane :beta_staging do
    build_app(
      scheme: "staging" # The iOS scheme matching your flavor
    )
    firebase_app_distribution(
      app: "1:905655582501:ios:011d5b2a327c95716ae4cc", # iOS Firebase App ID for flavor1
      testers: "Sivsovanpanhavorn@gmail.com",
      release_notes: "Release notes for Flavor1 staging test",
      ipa_path: "../build/ios/ipa/Flavor1.ipa" # Adjust the path if needed
    )
  end
end
